//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SolaComm.rc
//

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_SOLASUMMARYDLG		102

#define IDD_CHCONFIGDLG			200
#define IDD_DIGITALIODLG		201
#define IDD_ALERTLOGDLG			202
#define IDD_SYSTEMIDDLG			203
#define IDD_ODRESETCFGDLG		204
#define IDD_DHWCONFIGDLG		205
#define IDD_LLSTATUSDLG			206
#define IDD_LLCONFIGDLG			207
#define IDD_LOCKOUTLOGDLG		208
#define IDD_LOCKOUTRECORDDLG	209
#define IDD_MODCONFIGDLG		210
#define IDD_BCCONFIGDLG			211
#define IDD_LIMCONFIGDLG		212
#define IDD_PUMPCONFIGDLG		213
#define IDD_POLLINGDLG			214
#define IDD_SAVERESTOREDLG		215
#define IDD_LOADPARMSDLG		216

#define IDD_SYSTEMIDUIBOX		300
#define IDD_UINUMERIC	301
#define IDD_UIMULTI		302
#define IDD_UITIME		303
#define IDD_UIBITMASK	304
#define IDD_ODRESETLINEDLG		307
#define IDD_SYSTEMIDUINUMERIC	315
#define IDD_SYSTEMIDUITIME		317
#define IDD_CONFIGUIPERCENT		322
#define IDD_MBSERVERIP			326

#define IDC_SYSTEMIDUIEDIT		400
#define IDC_UINUMEDIT	401
#define IDC_UIMULTICOMBO	402
#define IDC_ODRESETLINEBTN		407
#define IDC_SYSTEMIDUINUMEDIT	415
#define IDC_SYSTEMIDUITIMEEDIT	417
#define IDC_CONFIGUIPCTEDIT	422
#define IDC_CONFIGUIPCTEDITDEC	423
#define IDC_TXTFILECONTENTS		424
#define IDC_TXTLOADPARMSSTATUS	425

#define IDD_DLGMAIN				103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_SOLACOMM			107
#define IDI_SMALL				108
#define IDC_SOLACOMM			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif

#define IDC_TXTUIBMMASKVALUE	199
#define IDC_TXTUIBMBIT00		200
#define IDC_TXTUIBMBIT01		201
#define IDC_TXTUIBMBIT02		202
#define IDC_TXTUIBMBIT03		203
#define IDC_TXTUIBMBIT04		204
#define IDC_TXTUIBMBIT05		205
#define IDC_TXTUIBMBIT06		206
#define IDC_TXTUIBMBIT07		207
#define IDC_TXTUIBMBIT08		208
#define IDC_TXTUIBMBIT09		209
#define IDC_TXTUIBMBIT10		210
#define IDC_TXTUIBMBIT11		211
#define IDC_TXTUIBMBIT12		212
#define IDC_TXTUIBMBIT13		213
#define IDC_TXTUIBMBIT14		214
#define IDC_TXTUIBMBIT15		215

#define IDD_NOTICEBOX			600
#define IDM_STARTNOTICE				601
#define IDM_STOPNOTICE				602
#define IDM_SETNOTICETXT			604
#define IDT_TIMER01					605

#define IDC_TXTNOTICE				603

#define IDC_TXTTIME				1002

#define TXTIDBASE				2000
#define LBLIDBASE				7000
#define BTNIDBASE				8000
#define HHSPINIDBASE			9000
#define MMSPINIDBASE			10000
#define SSSPINIDBASE			11000
#define HHEDITIDBASE			12000
#define MMEDITIDBASE			13000
#define SSEDITIDBASE			14000
#define NUMPROPPAGES			15

#define IDC_TXTCURLOCKOUTCODE		TXTIDBASE + 0x0022
//#define IDC_TXTALARMREASON		TXTIDBASE + 0x0023
#define IDC_TXTCURHOLDCODE			TXTIDBASE + 0x0028
#define IDC_TXTDEMAND			TXTIDBASE + 0x0006
#define IDC_TXTBURNERSTATE		TXTIDBASE + 0x0021
#define IDC_TXTBURNERSEQTIME		TXTIDBASE + 0x0026
#define IDC_TXTBURNERDLYTIME		TXTIDBASE + 0x0027
#define IDC_TXTDHWPRICNT		TXTIDBASE + 0x0052
#define IDC_TXTCHPUMPSTATUS		TXTIDBASE + 0x0060
#define IDC_TXTDHWPUMPSTATUS	TXTIDBASE + 0x0064
#define IDC_TXTSYSPUMPSTATUS	TXTIDBASE + 0x0069
#define IDC_TXTBLRPUMPSTATUS	TXTIDBASE + 0x006C
#define IDC_TXTTSLLSETPOINT		TXTIDBASE + 0x0012
#define IDC_TXTINLETTEMP		TXTIDBASE + 0x000B
#define IDC_TXTOUTLETTEMP		TXTIDBASE + 0x0007
#define IDC_TXTSYSTEMTEMP		TXTIDBASE + 0x00AE
#define IDC_TXTSTACKTEMP		TXTIDBASE + 0x000E
#define IDC_TXT420INPUT			TXTIDBASE + 0x000F
//#define IDC_TXTODTEMP			TXTIDBASE + 0x000D
#define IDC_TXTODTEMP			TXTIDBASE + 0x00AA
//#define IDC_TXTODTEMP			TXTIDBASE + 0x0331
#define IDC_TXTFIRINGRATE		TXTIDBASE + 0x0008
#define IDC_TXTFANSPEED			TXTIDBASE + 0x0009
#define IDC_TXTFLAMESIG			TXTIDBASE + 0x000A
#define IDC_TXTDHWTEMP			TXTIDBASE + 0x000C
#define IDC_TXTCHSETPT			TXTIDBASE + 0x0010
#define IDC_TXTDHWSETPT			TXTIDBASE + 0x0011
#define IDC_TXTOUTLETOPSENSORSTATE	TXTIDBASE + 0x002E
#define IDC_TXTDHWOPSENSORSTATE		TXTIDBASE + 0x002F
#define IDC_TXTOUTLETSENSORSTATE	TXTIDBASE + 0x0030
#define IDC_TXTSYSTEMSENSORSTATE	TXTIDBASE + 0x00AF
#define IDC_TXTINLETSENSORSTATE		TXTIDBASE + 0x0031
#define IDC_TXTDHWSENSORSTATE		TXTIDBASE + 0x0032
#define IDC_TXTSTACKSENSORSTATE		TXTIDBASE + 0x0033
#define IDC_TXTODSENSORSTATE		TXTIDBASE + 0x0034
#define IDC_TXT420SENSORSTATE		TXTIDBASE + 0x0035
#define IDC_TXTSTACKOPSENSORSTATE	TXTIDBASE + 0x0037
#define IDC_TXTACTVRATELIM			TXTIDBASE + 0x0038
#define IDC_TXTLTDRATE				TXTIDBASE + 0x0039
#define IDC_TXTACTVRATEOVRD			TXTIDBASE + 0x003A
#define IDC_TXTOVRDRATE				TXTIDBASE + 0x003B
#define IDC_TXTDEMANDRATE			TXTIDBASE + 0x003C
#define IDC_TXTCHONHYST				TXTIDBASE + 0x0047
#define IDC_TXTCHOFFHYST			TXTIDBASE + 0x0048
#define IDC_TXTACTVDHWONHYST		TXTIDBASE + 0x0058
#define IDC_TXTACTVDHWOFFHYST		TXTIDBASE + 0x0059
#define IDC_TXTACTVSETPOINT			TXTIDBASE + 0x001D

#define IDC_LBLCURLOCKOUTCODE			LBLIDBASE + 0x0022
//#define IDC_TXTALARMREASON			LBLIDBASE + 0x0023
#define IDC_LBLCURHOLDCODE				LBLIDBASE + 0x0028
#define IDC_LBLDEMAND				LBLIDBASE + 0x0006
#define IDC_LBLBURNERSTATE			LBLIDBASE + 0x0021
#define IDC_LBLBURNERSEQTIME			LBLIDBASE + 0x0026
#define IDC_LBLBURNERDLYTIME			LBLIDBASE + 0x0027
#define IDC_LBLDHWPRICNT			LBLIDBASE + 0x0052
#define IDC_LBLCHPUMPSTATUS			LBLIDBASE + 0x0060
#define IDC_LBLDHWPUMPSTATUS		LBLIDBASE + 0x0064
#define IDC_LBLSYSPUMPSTATUS		LBLIDBASE + 0x0069
#define IDC_LBLBLRPUMPSTATUS		LBLIDBASE + 0x006C
#define IDC_LBLTSLLSETPOINT			LBLIDBASE + 0x0012
#define IDC_LBLINLETTEMP			LBLIDBASE + 0x000B
#define IDC_LBLOUTLETTEMP			LBLIDBASE + 0x0007
#define IDC_LBLSYSTEMTEMP			LBLIDBASE + 0x00AE
#define IDC_LBLSTACKTEMP			LBLIDBASE + 0x000E
#define IDC_LBL420INPUT				LBLIDBASE + 0x000F
//#define IDC_LBLODTEMP				LBLIDBASE + 0x000D
#define IDC_LBLODTEMP				LBLIDBASE + 0x00AA
//#define IDC_LBLODTEMP				LBLIDBASE + 0x0331
#define IDC_LBLFIRINGRATE			LBLIDBASE + 0x0008
#define IDC_LBLFANSPEED				LBLIDBASE + 0x0009
#define IDC_LBLFLAMESIG				LBLIDBASE + 0x000A
#define IDC_LBLDHWTEMP				LBLIDBASE + 0x000C
#define IDC_LBLCHSETPT				LBLIDBASE + 0x0010
#define IDC_LBLDHWSETPT				LBLIDBASE + 0x0011
#define IDC_LBLACTVRATELIM			LBLIDBASE + 0x0038
#define IDC_LBLLTDRATE				LBLIDBASE + 0x0039
#define IDC_LBLACTVRATEOVRD			LBLIDBASE + 0x003A
#define IDC_LBLOVRDRATE				LBLIDBASE + 0x003B
#define IDC_LBLDEMANDRATE			LBLIDBASE + 0x003C
#define IDC_LBLCHONHYST				LBLIDBASE + 0x0047
#define IDC_LBLCHOFFHYST			LBLIDBASE + 0x0048
#define IDC_LBLACTVDHWONHYST		LBLIDBASE + 0x0058
#define IDC_LBLACTVDHWOFFHYST		LBLIDBASE + 0x0059
#define IDC_LBLACTVSETPOINT			LBLIDBASE + 0x001D
//#define IDC_LBLTEMPUNITS			LBLIDBASE + 0x00B2

//Modulation configuration dialog fields
#define IDC_LBLMODOUTPUT				LBLIDBASE + 0x00C0
#define IDC_LBLMODCHMAXRATE		LBLIDBASE + 0x00C1
#define IDC_LBLMODDWHMAXRATE				LBLIDBASE + 0x00C2
#define IDC_LBLMODMINRATE			LBLIDBASE + 0x00C3
#define IDC_LBLMODPREPURGERATE		LBLIDBASE + 0x00C4
#define IDC_LBLMODLIGHTOFFRATE		LBLIDBASE + 0x00C5
#define IDC_LBLMODPOSTPURGERATE		LBLIDBASE + 0x00C6
#define IDC_LBLMODCHFORCEDRATE		LBLIDBASE + 0x00C7
#define IDC_LBLMODCHFORCEDRATETIME				LBLIDBASE + 0x00C8
#define IDC_LBLMODDHWFORCEDRATE				LBLIDBASE + 0x00C9
#define IDC_LBLMODDHWFORCEDRATETIME				LBLIDBASE + 0x00CA
#define IDC_LBLMODBURNERSWITCH				LBLIDBASE + 0x00CB
#define IDC_LBLMODFIRINGRATECTRL		LBLIDBASE + 0x00CC
#define IDC_LBLMODMANUALFIRINGRATE		LBLIDBASE + 0x00CD
#define IDC_LBLMODANALOGOUTPUTHYST		LBLIDBASE + 0x00CE
#define IDC_LBLMODSTANDBYRATE			LBLIDBASE + 0x00CF
#define IDC_LBLFRZPROTRATE0V4MA			LBLIDBASE + 0x0216

#define IDC_TXTMODOUTPUT			TXTIDBASE + 0x00C0
#define IDC_TXTMODCHMAXRATE			TXTIDBASE + 0x00C1
#define IDC_TXTMODDWHMAXRATE		TXTIDBASE + 0x00C2
#define IDC_TXTMODMINRATE			TXTIDBASE + 0x00C3
#define IDC_TXTMODPREPURGERATE		TXTIDBASE + 0x00C4
#define IDC_TXTMODLIGHTOFFRATE		TXTIDBASE + 0x00C5
#define IDC_TXTMODPOSTPURGERATE		TXTIDBASE + 0x00C6
#define IDC_TXTMODCHFORCEDRATE		TXTIDBASE + 0x00C7
#define IDC_TXTMODCHFORCEDRATETIME				TXTIDBASE + 0x00C8
#define IDC_TXTMODDHWFORCEDRATE				TXTIDBASE + 0x00C9
#define IDC_TXTMODDHWFORCEDRATETIME				TXTIDBASE + 0x00CA
#define IDC_TXTMODBURNERSWITCH				TXTIDBASE + 0x00CB
#define IDC_TXTMODFIRINGRATECTRL		TXTIDBASE + 0x00CC
#define IDC_TXTMODMANUALFIRINGRATE		TXTIDBASE + 0x00CD
#define IDC_TXTMODANALOGOUTPUTHYST		TXTIDBASE + 0x00CE
#define IDC_TXTMODSTANDBYRATE			TXTIDBASE + 0x00CF
#define IDC_TXTFRZPROTRATE0V4MA			TXTIDBASE + 0x0216

/* Fan configuration dialog fields */
#define IDC_LBLABSMAXFANSPD				LBLIDBASE + 0x0100
#define IDC_LBLABSMINFANSPD				LBLIDBASE + 0x0101
#define IDC_LBLFANPWMFREQ				LBLIDBASE + 0x0102
#define IDC_LBLFANPULSPERREV			LBLIDBASE + 0x0103
#define IDC_LBLFANSPDUPRAMP				LBLIDBASE + 0x0104
#define IDC_LBLFANSLOWDNRAMP			LBLIDBASE + 0x0105
#define IDC_LBLFANGAINUP				LBLIDBASE + 0x0106
#define IDC_LBLFANGAINDOWN				LBLIDBASE + 0x0107
#define IDC_LBLFANMINDUTYCYCLE			LBLIDBASE + 0x0108

#define IDC_TXTABSMAXFANSPD				TXTIDBASE + 0x0100
#define IDC_TXTABSMINFANSPD				TXTIDBASE + 0x0101
#define IDC_TXTFANPWMFREQ				TXTIDBASE + 0x0102
#define IDC_TXTFANPULSPERREV			TXTIDBASE + 0x0103
#define IDC_TXTFANSPDUPRAMP				TXTIDBASE + 0x0104
#define IDC_TXTFANSLOWDNRAMP			TXTIDBASE + 0x0105
#define IDC_TXTFANGAINUP				TXTIDBASE + 0x0106
#define IDC_TXTFANGAINDOWN				TXTIDBASE + 0x0107
#define IDC_TXTFANMINDUTYCYCLE			TXTIDBASE + 0x0108

//#define IDC_CHHYSTSTHOURSPIN		HHSPINIDBASE + 0x00C8
//#define IDC_CHHYSTSTMINSPIN			MMSPINIDBASE + 0x00C8
//#define IDC_CHHYSTSTSECSPIN			SSSPINIDBASE + 0x00DB
#define IDC_MODHOUREDIT		HHEDITIDBASE + 0x00C8
#define IDC_MODMINEDIT			MMEDITIDBASE + 0x00C8
#define IDC_MODSECEDIT			SSEDITIDBASE + 0x00DB

#define IDC_LIMHOUREDIT			HHEDITIDBASE + 0x01E7
#define IDC_LIMMINEDIT			MMEDITIDBASE + 0x01E7
#define IDC_LIMSECEDIT			SSEDITIDBASE + 0x01E7

//CH configuration dialog fields
#define IDC_LBLCHENABLE				LBLIDBASE + 0x00D0
#define IDC_LBLCHDEMANDSOURCE		LBLIDBASE + 0x00D1
#define IDC_LBLCHSENSOR				LBLIDBASE + 0x00D2
#define IDC_LBLCHSETPOINT			LBLIDBASE + 0x00D3
#define IDC_LBLCHTODSETPOINT		LBLIDBASE + 0x00D4
#define IDC_LBLCHONHYSTERESIS		LBLIDBASE + 0x00D5
#define IDC_LBLCHOFFHYSTERESIS		LBLIDBASE + 0x00D6
#define IDC_LBLCHODRESETENABLE		LBLIDBASE + 0x00D7
#define IDC_LBLCHPGAIN				LBLIDBASE + 0x00D8
#define IDC_LBLCHIGAIN				LBLIDBASE + 0x00D9
#define IDC_LBLCHDGAIN				LBLIDBASE + 0x00DA
#define IDC_LBLCHHYSTSTEPTIME		LBLIDBASE + 0x00DB
#define IDC_LBLANALOGINPUTHYST		LBLIDBASE + 0x021F
#define IDC_LBLCHREMOTECONTROL		LBLIDBASE + 0x00DF
#define IDC_LBLWWSDENABLE			LBLIDBASE + 0x0273
#define IDC_LBLWWSDSETPOINT			LBLIDBASE + 0x0274
#define IDC_LBLCHFROSTPROTENABLE	LBLIDBASE + 0x0210
#define IDC_LBLCHFROSTPROTSETPT		LBLIDBASE + 0x0212
#define IDC_LBLCHMODBUSSTAT			LBLIDBASE + 0x0241
#define IDC_LBLCHSTPTSRC			LBLIDBASE + 0x0242
#define IDC_LBLCHMODBUSSTPT			LBLIDBASE + 0x0243
#define IDC_LBLCHMODRATESRC			LBLIDBASE + 0x0244
#define IDC_LBLCHMODBUSRATE			LBLIDBASE + 0x0245
#define IDC_LBLCHPTYVSLL			LBLIDBASE + 0x0246
#define IDC_LBL4MATEMP				LBLIDBASE + 0x0247
#define IDC_LBL20MATEMP				LBLIDBASE + 0x0248

#define IDC_TXTCHENABLE				TXTIDBASE + 0x00D0
#define IDC_TXTCHDEMANDSOURCE		TXTIDBASE + 0x00D1
#define IDC_TXTCHSENSOR				TXTIDBASE + 0x00D2
#define IDC_TXTCHSETPOINT			TXTIDBASE + 0x00D3
#define IDC_TXTCHTODSETPOINT		TXTIDBASE + 0x00D4
#define IDC_TXTCHONHYSTERESIS		TXTIDBASE + 0x00D5
#define IDC_TXTCHOFFHYSTERESIS		TXTIDBASE + 0x00D6
#define IDC_TXTCHODRESET			TXTIDBASE + 0x00D7
#define IDC_TXTCHPGAIN				TXTIDBASE + 0x00D8
#define IDC_TXTCHIGAIN				TXTIDBASE + 0x00D9
#define IDC_TXTCHDGAIN				TXTIDBASE + 0x00DA
#define IDC_TXTCHHYSTSTEPTIME		TXTIDBASE + 0x00DB
#define IDC_TXTANALOGINPUTHYST		TXTIDBASE + 0x021F
#define IDC_TXTWWSDENABLE			TXTIDBASE + 0x0273
#define IDC_TXTWWSDSETPOINT			TXTIDBASE + 0x0274
#define IDC_TXTCHFROSTPROTENABLE	TXTIDBASE + 0x0210
#define IDC_TXTCHFROSTPROTSETPT		TXTIDBASE + 0x0212
#define IDC_TXTCHMODBUSSTAT			TXTIDBASE + 0x0241
#define IDC_TXTCHSTPTSRC			TXTIDBASE + 0x0242
#define IDC_TXTCHMODBUSSTPT			TXTIDBASE + 0x0243
#define IDC_TXTCHMODRATESRC			TXTIDBASE + 0x0244
#define IDC_TXTCHMODBUSRATE			TXTIDBASE + 0x0245
#define IDC_TXTCHPTYVSLL			TXTIDBASE + 0x0246
#define IDC_TXT4MATEMP				TXTIDBASE + 0x0247
#define IDC_TXT20MATEMP				TXTIDBASE + 0x0248

#define IDC_CHHYSTSTHOURSPIN		HHSPINIDBASE + 0x00DB
#define IDC_CHHYSTSTMINSPIN			MMSPINIDBASE + 0x00DB
#define IDC_CHHYSTSTSECSPIN			SSSPINIDBASE + 0x00DB
#define IDC_CHHYSTSTHOUREDIT		HHEDITIDBASE + 0x00DB
#define IDC_CHHYSTSTMINEDIT			MMEDITIDBASE + 0x00DB
#define IDC_CHHYSTSTSECEDIT			SSEDITIDBASE + 0x00DB

#define IDC_LBLDHWENABLE			LBLIDBASE + 0x01C0
#define IDC_LBLDHWDEMANDSWITCH		LBLIDBASE + 0x01C1
#define IDC_LBLDHWDHWPRIORITYVSCH	LBLIDBASE + 0x01C2
#define IDC_LBLDHWDHWPRIORITYVSLL	LBLIDBASE + 0x01C3
#define IDC_LBLDHWDHWPRIORITYTIME	LBLIDBASE + 0x01C4
#define IDC_LBLDHWSETPOINT			LBLIDBASE + 0x01C5
#define IDC_LBLDHWTODSETPOINT		LBLIDBASE + 0x01C6
#define IDC_LBLDHWONHYSTERESIS		LBLIDBASE + 0x01C7
#define IDC_LBLDHWOFFHYSTERESIS		LBLIDBASE + 0x01C8
#define IDC_LBLDHWPGAIN				LBLIDBASE + 0x01C9
#define IDC_LBLDHWIGAIN				LBLIDBASE + 0x01CA
#define IDC_LBLDHWDGAIN				LBLIDBASE + 0x01CB
#define IDC_LBLDHWHYSTSTEPTIME		LBLIDBASE + 0x01CC
#define IDC_LBLDHWMODSENSOR			LBLIDBASE + 0x01CD
#define IDC_LBLDHWPRIORITYSRC		LBLIDBASE + 0x01CF
#define IDC_LBLDHWFROSTPROTENABLE	LBLIDBASE + 0x0211

#define IDC_TXTDHWENABLE			TXTIDBASE + 0x01C0
#define IDC_TXTDHWDEMANDSWITCH		TXTIDBASE + 0x01C1
#define IDC_TXTDHWDHWPRIORITYVSCH	TXTIDBASE + 0x01C2
#define IDC_TXTDHWDHWPRIORITYVSLL	TXTIDBASE + 0x01C3
#define IDC_TXTDHWDHWPRIORITYTIME	TXTIDBASE + 0x01C4
#define IDC_TXTDHWSETPOINT			TXTIDBASE + 0x01C5
#define IDC_TXTDHWTODSETPOINT		TXTIDBASE + 0x01C6
#define IDC_TXTDHWONHYSTERESIS		TXTIDBASE + 0x01C7
#define IDC_TXTDHWOFFHYSTERESIS		TXTIDBASE + 0x01C8
#define IDC_TXTDHWPGAIN				TXTIDBASE + 0x01C9
#define IDC_TXTDHWIGAIN				TXTIDBASE + 0x01CA
#define IDC_TXTDHWDGAIN				TXTIDBASE + 0x01CB
#define IDC_TXTDHWHYSTSTEPTIME		TXTIDBASE + 0x01CC
#define IDC_TXTDHWMODSENSOR			TXTIDBASE + 0x01CD
#define IDC_TXTDHWPRIORITYSRC		TXTIDBASE + 0x01CF
#define IDC_TXTDHWFROSTPROTENABLE	TXTIDBASE + 0x0211

#define IDC_DHWHYSTSTHOURSPIN		HHSPINIDBASE + 0x01CB
#define IDC_DHWHYSTSTMINSPIN		MMSPINIDBASE + 0x01CB
#define IDC_DHWHYSTSTSECSPIN		SSSPINIDBASE + 0x01CB
#define IDC_DHWHYSTSTHOUREDIT		HHEDITIDBASE + 0x01CB
#define IDC_DHWHYSTSTMINEDIT		MMEDITIDBASE + 0x01CB
#define IDC_DHWHYSTSTSECEDIT		SSEDITIDBASE + 0x01CB

/* DHW Storage configuration fields */
#define IDC_LBLDHWSTORAGEENABLE		LBLIDBASE + 0x01F8
#define IDC_LBLDHWSTORAGETIME		LBLIDBASE + 0x01F9
#define IDC_LBLDHWSTORAGESETPOINT	LBLIDBASE + 0x01FA
#define IDC_LBLDHWSTORAGEONHYST		LBLIDBASE + 0x01FB
#define IDC_LBLDHWSTORAGEOFFHYST	LBLIDBASE + 0x01FC
#define IDC_LBLDHWSTORAGEPTYMETHOD	LBLIDBASE + 0x01FD
#define IDC_LBLDHWDEMANDONTEMP		LBLIDBASE + 0x01FE
#define IDC_LBLDHWDEMANDOFFTEMP		LBLIDBASE + 0x01FF

#define IDC_TXTDHWSTORAGEENABLE		TXTIDBASE + 0x01F8
#define IDC_TXTDHWSTORAGETIME		TXTIDBASE + 0x01F9
#define IDC_TXTDHWSTORAGESETPOINT	TXTIDBASE + 0x01FA
#define IDC_TXTDHWSTORAGEONHYST		TXTIDBASE + 0x01FB
#define IDC_TXTDHWSTORAGEOFFHYST	TXTIDBASE + 0x01FC
#define IDC_TXTDHWSTORAGEPTYMETHOD	TXTIDBASE + 0x01FD
#define IDC_TXTDHWDEMANDONTEMP		TXTIDBASE + 0x01FE
#define IDC_TXTDHWDEMANDOFFTEMP		TXTIDBASE + 0x01FF

/* Pump configuration fields */
#define IDC_LBLCHPUMPOUTPUT			LBLIDBASE + 0x0110
#define IDC_LBLCHPUMPCTRL			LBLIDBASE + 0x0111
#define IDC_LBLCHPUMPOVRNTIME		LBLIDBASE + 0x0112
#define IDC_LBLCHPUMPFPOVRNTIME		LBLIDBASE + 0x0113
#define IDC_LBLDHWPUMPOUTPUT		LBLIDBASE + 0x0114
#define IDC_LBLDHWPUMPCTRL			LBLIDBASE + 0x0115
#define IDC_LBLDHWPUMPOVRNTIME		LBLIDBASE + 0x0116
#define IDC_LBLDHWPUMPFPOVRNTIME	LBLIDBASE + 0x0117
#define IDC_LBLDHWPUMPSTRTDLY		LBLIDBASE + 0x0118
#define IDC_LBLBLRPUMPOUTPUT		LBLIDBASE + 0x0119
#define IDC_LBLBLRPUMPCTRL			LBLIDBASE + 0x011A
#define IDC_LBLBLRPUMPOVRNTIME		LBLIDBASE + 0x011B
#define IDC_LBLAUX1PUMPOUTPUT		LBLIDBASE + 0x011C
#define IDC_LBLAUX1PUMPCTRL			LBLIDBASE + 0x011D
#define IDC_LBLPUMPRESERVED			LBLIDBASE + 0x011E
#define IDC_LBLSYSPUMPOUTPUT		LBLIDBASE + 0x011F
#define IDC_LBLSYSPUMPCTRL			LBLIDBASE + 0x0120
#define IDC_LBLSYSPUMPOVRNTIME		LBLIDBASE + 0x0121
#define IDC_LBLPUMPXRCSINTRVL		LBLIDBASE + 0x0122
#define IDC_LBLPUMPXRCSTIME			LBLIDBASE + 0x0123
#define IDC_LBLCHPUMPSTRTDLY		LBLIDBASE + 0x0124
#define IDC_LBLBLRPUMPSTRTDLY		LBLIDBASE + 0x0125
#define IDC_LBLSYSPUMPSTRTDLY		LBLIDBASE + 0x0126
#define IDC_LBLAUX1PUMPSTRTDLY		LBLIDBASE + 0x0127
#define IDC_LBLCHPUMPOPTS1			LBLIDBASE + 0x0128
#define IDC_LBLCHPUMPOPTS2			LBLIDBASE + 0x0129
#define IDC_LBLDHWPUMPOPTS1			LBLIDBASE + 0x012A
#define IDC_LBLDHWPUMPOPTS2			LBLIDBASE + 0x012B
#define IDC_LBLBLRPUMPOPTS1			LBLIDBASE + 0x012C
#define IDC_LBLBLRPUMPOPTS2			LBLIDBASE + 0x012D
#define IDC_LBLSYSPUMPOPTS1			LBLIDBASE + 0x012E
#define IDC_LBLSYSPUMPOPTS2			LBLIDBASE + 0x012F

#define IDC_TXTCHPUMPOUTPUT			TXTIDBASE + 0x0110
#define IDC_TXTCHPUMPCTRL			TXTIDBASE + 0x0111
#define IDC_TXTCHPUMPOVRNTIME		TXTIDBASE + 0x0112
#define IDC_TXTCHPUMPFPOVRNTIME		TXTIDBASE + 0x0113
#define IDC_TXTDHWPUMPOUTPUT		TXTIDBASE + 0x0114
#define IDC_TXTDHWPUMPCTRL			TXTIDBASE + 0x0115
#define IDC_TXTDHWPUMPOVRNTIME		TXTIDBASE + 0x0116
#define IDC_TXTDHWPUMPFPOVRNTIME	TXTIDBASE + 0x0117
#define IDC_TXTDHWPUMPSTRTDLY		TXTIDBASE + 0x0118
#define IDC_TXTBLRPUMPOUTPUT		TXTIDBASE + 0x0119
#define IDC_TXTBLRPUMPCTRL			TXTIDBASE + 0x011A
#define IDC_TXTBLRPUMPOVRNTIME		TXTIDBASE + 0x011B
#define IDC_TXTAUX1PUMPOUTPUT		TXTIDBASE + 0x011C
#define IDC_TXTAUX1PUMPCTRL			TXTIDBASE + 0x011D
#define IDC_TXTPUMPRESERVED			TXTIDBASE + 0x011E
#define IDC_TXTSYSPUMPOUTPUT		TXTIDBASE + 0x011F
#define IDC_TXTSYSPUMPCTRL			TXTIDBASE + 0x0120
#define IDC_TXTSYSPUMPOVRNTIME		TXTIDBASE + 0x0121
#define IDC_TXTPUMPXRCSINTRVL		TXTIDBASE + 0x0122
#define IDC_TXTPUMPXRCSTIME			TXTIDBASE + 0x0123
#define IDC_TXTCHPUMPSTRTDLY		TXTIDBASE + 0x0124
#define IDC_TXTBLRPUMPSTRTDLY		TXTIDBASE + 0x0125
#define IDC_TXTSYSPUMPSTRTDLY		TXTIDBASE + 0x0126
#define IDC_TXTAUX1PUMPSTRTDLY		TXTIDBASE + 0x0127
#define IDC_TXTCHPUMPOPTS1			TXTIDBASE + 0x0128
#define IDC_TXTCHPUMPOPTS2			TXTIDBASE + 0x0129
#define IDC_TXTDHWPUMPOPTS1			TXTIDBASE + 0x012A
#define IDC_TXTDHWPUMPOPTS2			TXTIDBASE + 0x012B
#define IDC_TXTBLRPUMPOPTS1			TXTIDBASE + 0x012C
#define IDC_TXTBLRPUMPOPTS2			TXTIDBASE + 0x012D
#define IDC_TXTSYSPUMPOPTS1			TXTIDBASE + 0x012E
#define IDC_TXTSYSPUMPOPTS2			TXTIDBASE + 0x012F

/* Limits configuration fields */
#define IDC_LBLOUTHILIMSTPT			LBLIDBASE + 0x01D0
#define IDC_LBLOUTHILIMRESP			LBLIDBASE + 0x01D1
#define IDC_LBLSTACKLIMENBL			LBLIDBASE + 0x01D2
#define IDC_LBLSTACKLIMSTPT			LBLIDBASE + 0x01D3
#define IDC_LBLSTACKLIMRESP			LBLIDBASE + 0x01D4
#define IDC_LBLSTACKLIMDLY			LBLIDBASE + 0x01D5
#define IDC_LBLDELTATINOUTENBL		LBLIDBASE + 0x01D6
#define IDC_LBLDELTATINOUTDIFF		LBLIDBASE + 0x01D7
#define IDC_LBLDELTATRESP			LBLIDBASE + 0x01D8
#define IDC_LBLDELTATDLY			LBLIDBASE + 0x01D9
#define IDC_LBLDHWHILIMENBL			LBLIDBASE + 0x01DA
#define IDC_LBLDHWHILIMSTPT			LBLIDBASE + 0x01DB
#define IDC_LBLDHWHILIMRESP			LBLIDBASE + 0x01DC
#define IDC_LBLCHSLOWSTRTENBL		LBLIDBASE + 0x01DD
#define IDC_LBLDHWSLOWSTRTENBL		LBLIDBASE + 0x01DE
#define IDC_LBLSLOWSTARTRAMP		LBLIDBASE + 0x01DF
#define IDC_LBLSLOWSTARTSTPT		LBLIDBASE + 0x01E0
#define IDC_LBLOUTTRISEENBL			LBLIDBASE + 0x01E1
#define IDC_LBLOUTTRISEDEG			LBLIDBASE + 0x01E2
#define IDC_LBLOUTTRISEDLY			LBLIDBASE + 0x01E3
#define IDC_LBLOUTHILIMENBL			LBLIDBASE + 0x01E4
#define IDC_LBLDELTARETRYLIM		LBLIDBASE + 0x01E5
#define IDC_LBLDELTATRATELIMENBL	LBLIDBASE + 0x01E6
#define IDC_LBLDELTATINVLIMTIME		LBLIDBASE + 0x01E7
#define IDC_LBLDELTATINVLIMRESP		LBLIDBASE + 0x01E8
#define IDC_LBLDELTATXCHGROUTENBL	LBLIDBASE + 0x01E9
#define IDC_LBLDELTATXCHGROUTDIFF	LBLIDBASE + 0x01EA
#define IDC_LBLXCHGRTRISEENBL		LBLIDBASE + 0x01EB
#define IDC_LBLTRISERESP			LBLIDBASE + 0x01EC
#define IDC_LBLTRISERETRYLIM		LBLIDBASE + 0x01ED
#define IDC_LBLDELTATINXCHGRENBL	LBLIDBASE + 0x01EE
#define IDC_LBLDELTATINXCHGRDIFF	LBLIDBASE + 0x01EF

#define IDC_TXTOUTHILIMSTPT			TXTIDBASE + 0x01D0
#define IDC_TXTOUTHILIMRESP			TXTIDBASE + 0x01D1
#define IDC_TXTSTACKLIMENBL			TXTIDBASE + 0x01D2
#define IDC_TXTSTACKLIMSTPT			TXTIDBASE + 0x01D3
#define IDC_TXTSTACKLIMRESP			TXTIDBASE + 0x01D4
#define IDC_TXTSTACKLIMDLY			TXTIDBASE + 0x01D5
#define IDC_TXTDELTATINOUTENBL		TXTIDBASE + 0x01D6
#define IDC_TXTDELTATINOUTDIFF		TXTIDBASE + 0x01D7
#define IDC_TXTDELTATRESP			TXTIDBASE + 0x01D8
#define IDC_TXTDELTATDLY			TXTIDBASE + 0x01D9
#define IDC_TXTDHWHILIMENBL			TXTIDBASE + 0x01DA
#define IDC_TXTDHWHILIMSTPT			TXTIDBASE + 0x01DB
#define IDC_TXTDHWHILIMRESP			TXTIDBASE + 0x01DC
#define IDC_TXTCHSLOWSTRTENBL		TXTIDBASE + 0x01DD
#define IDC_TXTDHWSLOWSTRTENBL		TXTIDBASE + 0x01DE
#define IDC_TXTSLOWSTARTRAMP		TXTIDBASE + 0x01DF
#define IDC_TXTSLOWSTARTSTPT		TXTIDBASE + 0x01E0
#define IDC_TXTOUTTRISEENBL			TXTIDBASE + 0x01E1
#define IDC_TXTOUTTRISEDEG			TXTIDBASE + 0x01E2
#define IDC_TXTOUTTRISEDLY			TXTIDBASE + 0x01E3
#define IDC_TXTOUTHILIMENBL			TXTIDBASE + 0x01E4
#define IDC_TXTDELTARETRYLIM		TXTIDBASE + 0x01E5
#define IDC_TXTDELTATRATELIMENBL	TXTIDBASE + 0x01E6
#define IDC_TXTDELTATINVLIMTIME		TXTIDBASE + 0x01E7
#define IDC_TXTDELTATINVLIMRESP		TXTIDBASE + 0x01E8
#define IDC_TXTDELTATXCHGROUTENBL	TXTIDBASE + 0x01E9
#define IDC_TXTDELTATXCHGROUTDIFF	TXTIDBASE + 0x01EA
#define IDC_TXTXCHGRTRISEENBL		TXTIDBASE + 0x01EB
#define IDC_TXTTRISERESP			TXTIDBASE + 0x01EC
#define IDC_TXTTRISERETRYLIM		TXTIDBASE + 0x01ED
#define IDC_TXTDELTATINXCHGRENBL	TXTIDBASE + 0x01EE
#define IDC_TXTDELTATINXCHGRDIFF	TXTIDBASE + 0x01EF

/* Extended Limits configuration fields */
#define IDC_LBLHXHIGHLIMITENBL		LBLIDBASE + 0x0250
#define IDC_LBLHXHIGHLIMITSTPT		LBLIDBASE + 0x0251
#define IDC_LBLHXHIGHLIMITRESP		LBLIDBASE + 0x0252
#define IDC_LBLHXHIGHLIMITDELAY		LBLIDBASE + 0x0253
#define IDC_LBLHXRETRYLIMIT			LBLIDBASE + 0x0254
#define IDC_LBLPRFRDOUTLETHILIM		LBLIDBASE + 0x0255
#define IDC_LBLPRFRDSTACKLIMSTPT	LBLIDBASE + 0x0256

#define IDC_TXTHXHIGHLIMITENBL		TXTIDBASE + 0x0250
#define IDC_TXTHXHIGHLIMITSTPT		TXTIDBASE + 0x0251
#define IDC_TXTHXHIGHLIMITRESP		TXTIDBASE + 0x0252
#define IDC_TXTHXHIGHLIMITDELAY		TXTIDBASE + 0x0253
#define IDC_TXTHXRETRYLIMIT			TXTIDBASE + 0x0254
#define IDC_TXTPRFRDOUTLETHILIM		TXTIDBASE + 0x0255
#define IDC_TXTPRFRDSTACKLIMSTPT	TXTIDBASE + 0x0256

/* Connector configuration fields */
#define IDC_LBLS1J84CONNTYPE		LBLIDBASE + 0x0260
#define IDC_LBLS2J86CONNTYPE		LBLIDBASE + 0x0261
#define IDC_LBLS3S4J8810CONNTYPE	LBLIDBASE + 0x0262
#define IDC_LBLS5J811CONNTYPE		LBLIDBASE + 0x0263
#define IDC_LBLS6S7J913CONNTYPE		LBLIDBASE + 0x0264
#define IDC_LBLS8S9J946CONNTYPE		LBLIDBASE + 0x0265
#define IDC_LBLS10J107CONNTYPE		LBLIDBASE + 0x0266
#define IDC_LBLODTEMPCORROFFSET		LBLIDBASE + 0x0267

#define IDC_TXTS1J84CONNTYPE		TXTIDBASE + 0x0260
#define IDC_TXTS2J86CONNTYPE		TXTIDBASE + 0x0261
#define IDC_TXTS3S4J8810CONNTYPE	TXTIDBASE + 0x0262
#define IDC_TXTS5J811CONNTYPE		TXTIDBASE + 0x0263
#define IDC_TXTS6S7J913CONNTYPE		TXTIDBASE + 0x0264
#define IDC_TXTS8S9J946CONNTYPE		TXTIDBASE + 0x0265
#define IDC_TXTS10J107CONNTYPE		TXTIDBASE + 0x0266
#define IDC_TXTODTEMPCORROFFSET		TXTIDBASE + 0x0267

/* Burner control configuration fields */
#define IDC_LBLBCIGNITIONSRC		LBLIDBASE + 0x00E0
#define IDC_LBLBCBLRHSIFUNC			LBLIDBASE + 0x00E1
#define IDC_LBLBCIGNITERONDUR		LBLIDBASE + 0x00E2
#define IDC_LBLBCPILOTTYPE			LBLIDBASE + 0x00E3
#define IDC_LBLBCFLAMESENSTYPE		LBLIDBASE + 0x00E4
#define IDC_LBLBCPURGERATEPRV		LBLIDBASE + 0x00E5
#define IDC_LBLBCLIGHTOFFRATEPRV	LBLIDBASE + 0x00E6
#define IDC_LBLBCPREPURGETIME		LBLIDBASE + 0x00E7
#define IDC_LBLBCPREIGNITIONTIME	LBLIDBASE + 0x00E8
#define IDC_LBLBCPFEP				LBLIDBASE + 0x00E9
#define IDC_LBLBCMFEP				LBLIDBASE + 0x00EA
#define IDC_LBLBCRUNSTABTIME		LBLIDBASE + 0x00EB
#define IDC_LBLBCPOSTPURGETIME		LBLIDBASE + 0x00EC
#define IDC_LBLBCILKSTRTCHKENBL		LBLIDBASE + 0x00ED
#define IDC_LBLBCILKOPENRESP		LBLIDBASE + 0x00EE
#define IDC_LBLBCIGNITEFAILRESP		LBLIDBASE + 0x00EF
#define IDC_LBLBCIGNITEFAILRETRIES	LBLIDBASE + 0x00F0
#define IDC_LBLBCIGNITEFAILDLY		LBLIDBASE + 0x00F1
#define IDC_LBLBCMFEPFLMFAILRESP	LBLIDBASE + 0x00F2
#define IDC_LBLBCRUNFLMFAILRESP		LBLIDBASE + 0x00F3
#define IDC_LBLBCPILOTTESTHOLD		LBLIDBASE + 0x00F4
//#define IDC_LBLBCRESERVED1		LBLIDBASE + 0x00F5
#define IDC_LBLBCIASENABLE			LBLIDBASE + 0x00F6
#define IDC_LBLBCIASSTRTCHKENBL		LBLIDBASE + 0x00F7
#define IDC_LBLBCLCIENABLE			LBLIDBASE + 0x00F8
#define IDC_LBLBCPIIENABLE			LBLIDBASE + 0x00F9
#define IDC_LBLBCFLMTHRESHHOLD		LBLIDBASE + 0x00FA
//#define IDC_LBLBCRESERVED2		LBLIDBASE + 0x00FB
//#define IDC_LBLBCRESERVED3		LBLIDBASE + 0x00FC
#define IDC_LBLBCILKBOUNCEDET		LBLIDBASE + 0x00FD
#define IDC_LBLBCFORCEDRECYCINT		LBLIDBASE + 0x00FE
#define IDC_LBLBCFANSPDERRRESP		LBLIDBASE + 0x00FF
#define IDC_LBLIASOPENMODENABLE		LBLIDBASE + 0x0218
#define IDC_LBLIASOPENRATEDIFF		LBLIDBASE + 0x0219
#define IDC_LBLIASOPENMODSTEPRATE	LBLIDBASE + 0x021a
#define IDC_LBLIASOPENMODSTEPTIME	LBLIDBASE + 0x021b
#define IDC_LBLIASCLOSEDRESPONSE	LBLIDBASE + 0x021c

#define IDC_TXTBCIGNITIONSRC		TXTIDBASE + 0x00E0
#define IDC_TXTBCBLRHSIFUNC			TXTIDBASE + 0x00E1
#define IDC_TXTBCIGNITERONDUR		TXTIDBASE + 0x00E2
#define IDC_TXTBCPILOTTYPE			TXTIDBASE + 0x00E3
#define IDC_TXTBCFLAMESENSTYPE		TXTIDBASE + 0x00E4
#define IDC_TXTBCPURGERATEPRV		TXTIDBASE + 0x00E5
#define IDC_TXTBCLIGHTOFFRATEPRV	TXTIDBASE + 0x00E6
#define IDC_TXTBCPREPURGETIME		TXTIDBASE + 0x00E7
#define IDC_TXTBCPREIGNITIONTIME	TXTIDBASE + 0x00E8
#define IDC_TXTBCPFEP				TXTIDBASE + 0x00E9
#define IDC_TXTBCMFEP				TXTIDBASE + 0x00EA
#define IDC_TXTBCRUNSTABTIME		TXTIDBASE + 0x00EB
#define IDC_TXTBCPOSTPURGETIME		TXTIDBASE + 0x00EC
#define IDC_TXTBCILKSTRTCHKENBL		TXTIDBASE + 0x00ED
#define IDC_TXTBCILKOPENRESP		TXTIDBASE + 0x00EE
#define IDC_TXTBCIGNITEFAILRESP		TXTIDBASE + 0x00EF
#define IDC_TXTBCIGNITEFAILRETRIES	TXTIDBASE + 0x00F0
#define IDC_TXTBCIGNITEFAILDLY		TXTIDBASE + 0x00F1
#define IDC_TXTBCMFEPFLMFAILRESP	TXTIDBASE + 0x00F2
#define IDC_TXTBCRUNFLMFAILRESP		TXTIDBASE + 0x00F3
#define IDC_TXTBCPILOTTESTHOLD		TXTIDBASE + 0x00F4
//#define IDC_TXTBCRESERVED1		TXTIDBASE + 0x00F5
#define IDC_TXTBCIASENABLE			TXTIDBASE + 0x00F6
#define IDC_TXTBCIASSTRTCHKENBL		TXTIDBASE + 0x00F7
#define IDC_TXTBCLCIENABLE			TXTIDBASE + 0x00F8
#define IDC_TXTBCPIIENABLE			TXTIDBASE + 0x00F9
#define IDC_TXTBCFLMTHRESHHOLD		TXTIDBASE + 0x00FA
//#define IDC_TXTBCRESERVED2		TXTIDBASE + 0x00FB
//#define IDC_TXTBCRESERVED3		TXTIDBASE + 0x00FC
#define IDC_TXTBCILKBOUNCEDET		TXTIDBASE + 0x00FD
#define IDC_TXTBCFORCEDRECYCINT		TXTIDBASE + 0x00FE
#define IDC_TXTBCFANSPDERRRESP		TXTIDBASE + 0x00FF
#define IDC_TXTIASOPENMODENABLE		TXTIDBASE + 0x0218
#define IDC_TXTIASOPENRATEDIFF		TXTIDBASE + 0x0219
#define IDC_TXTIASOPENMODSTEPRATE	TXTIDBASE + 0x021a
#define IDC_TXTIASOPENMODSTEPTIME	TXTIDBASE + 0x021b
#define IDC_TXTIASCLOSEDRESPONSE	TXTIDBASE + 0x021c

#define IDC_BCHOUREDIT				HHEDITIDBASE + 0x00E7
#define IDC_BCMINEDIT				MMEDITIDBASE + 0x00E7
#define IDC_BCSECEDIT				SSEDITIDBASE + 0x00E7

#define IDC_LBLLLFROSTPROTENABLE	LBLIDBASE + 0x0214
#define IDC_LBLLLFROSTPROTRATE		LBLIDBASE + 0x0215
#define IDC_LBLLLSLAVEENABLE		LBLIDBASE + 0x0220
#define IDC_LBLLLMASTERENABLE		LBLIDBASE + 0x0221
#define IDC_LBLLLSETPOINT			LBLIDBASE + 0x0222
#define IDC_LBLLLTODSETPOINT		LBLIDBASE + 0x0223
#define IDC_LBLLLODRESETNABLE		LBLIDBASE + 0x0224
#define IDC_LBLLLONHYSTERESIS		LBLIDBASE + 0x0225
#define IDC_LBLLLOFFHYSTERESIS		LBLIDBASE + 0x0226
#define IDC_LBLLLHYSTSTEPTIME		LBLIDBASE + 0x0227
#define IDC_LBLLLPGAIN				LBLIDBASE + 0x0228
#define IDC_LBLLLIGAIN				LBLIDBASE + 0x0229
#define IDC_LBLLLDGAIN				LBLIDBASE + 0x022A
#define IDC_LBLLLOPERATIONSWITCH	LBLIDBASE + 0x022B
#define IDC_LBLLLCHDEMANDSWITCH		LBLIDBASE + 0x022C
#define IDC_LBLLLCHSETPOINTSRC		LBLIDBASE + 0x022D
#define IDC_LBLLLMODULATIONSENSOR	LBLIDBASE + 0x022E
#define IDC_LBLLLBACKUPMODSENSOR	LBLIDBASE + 0x022F
#define IDC_LBLLLCH4MATEMP			LBLIDBASE + 0x0230
#define IDC_LBLLLCH20MATEMP			LBLIDBASE + 0x0231
#define IDC_LBLLLCHMODBUSSETPOINT	LBLIDBASE + 0x0232
#define IDC_LBLLLCHMODBUSSTAT		LBLIDBASE + 0x0233
#define IDC_LBLLLSLAVEMODE			LBLIDBASE + 0x0234
#define IDC_LBLLLSLAVECOMMAND		LBLIDBASE + 0x0235
#define IDC_LBLLLBASELOADRATE		LBLIDBASE + 0x0236
#define IDC_LBLLLFANDOCRATE			LBLIDBASE + 0x0237
#define IDC_LBLLLSLAVESEQORDER		LBLIDBASE + 0x0238
#define IDC_LBLLLMODBUSPORT			LBLIDBASE + 0x0239
#define IDC_LBLLLSLAVEDTFDELAY		LBLIDBASE + 0x023A
#define IDC_LBLLLSLAVECAPACITY		LBLIDBASE + 0x023B
#define IDC_LBLLLBASELDCOMMRATE		LBLIDBASE + 0x023C
#define IDC_LBLLLRATEALLOCMETHOD	LBLIDBASE + 0x023D
#define IDC_LBLLLLEADALLOCMETHOD	LBLIDBASE + 0x023E
#define IDC_LBLLLLAGALLOCMETHOD		LBLIDBASE + 0x023F
#define IDC_LBLLLDHWDEMANDSW		LBLIDBASE + 0x02C0
#define IDC_LBLLLDHWSETPOINT		LBLIDBASE + 0x02C1
#define IDC_LBLLLDHWPRIORITYVSCH	LBLIDBASE + 0x02C2
#define IDC_LBLLLRESERVED01			LBLIDBASE + 0x02C3
#define IDC_LBLLLRESERVED02			LBLIDBASE + 0x02C4
#define IDC_LBLLLRESERVED03			LBLIDBASE + 0x02C5
#define IDC_LBLLLRESERVED04			LBLIDBASE + 0x02C6
#define IDC_LBLLLRESERVED05			LBLIDBASE + 0x02C7
#define IDC_LBLLLRESERVED06			LBLIDBASE + 0x02C8
#define IDC_LBLLLSLVDROPOUTRTNCOMP	LBLIDBASE + 0x02C9
#define IDC_LBLLLADDSTGMTHD			LBLIDBASE + 0x02CA
#define IDC_LBLLLRESERVED07			LBLIDBASE + 0x02CB
#define IDC_LBLLLADDSTGDTCTTIME		LBLIDBASE + 0x02CC
#define IDC_LBLLLRESERVED08			LBLIDBASE + 0x02CD
#define IDC_LBLLLADDSTGERRTHRSHLD	LBLIDBASE + 0x02CE
#define IDC_LBLLLADDSTGRATEOFFSET	LBLIDBASE + 0x02CF
#define IDC_LBLLLADDSTGERRGAIN		LBLIDBASE + 0x02D0
#define IDC_LBLLLADDSTGRATEGAIN		LBLIDBASE + 0x02D1
#define IDC_LBLLLADDSTGINTRSTGDLY	LBLIDBASE + 0x02D2
#define IDC_LBLLLDROPSTGMTHD		LBLIDBASE + 0x02D3
#define IDC_LBLLLRESERVED09			LBLIDBASE + 0x02D4
#define IDC_LBLLLDROPSTGDTCTTIME	LBLIDBASE + 0x02D5
#define IDC_LBLLLRESERVED10			LBLIDBASE + 0x02D6
#define IDC_LBLLLDROPSTGERRTHRSHLD	LBLIDBASE + 0x02D7
#define IDC_LBLLLDROPSTGRATEOFFSET	LBLIDBASE + 0x02D8
#define IDC_LBLLLDROPSTGERRGAIN		LBLIDBASE + 0x02D9
#define IDC_LBLLLDROPSTGRATEGAIN	LBLIDBASE + 0x02DA
#define IDC_LBLLLDROPSTGINTRSTGDLY	LBLIDBASE + 0x02DB
#define IDC_LBLLLRESERVED11			LBLIDBASE + 0x02DC
#define IDC_LBLLLEADROTNTIME		LBLIDBASE + 0x02DD
#define IDC_LBLLFRCLEADROTNTIME		LBLIDBASE + 0x02DE
#define IDC_LBLLDHWTODSETPOINT		LBLIDBASE + 0x02DF
#define IDC_LBLLBLROFFOPTIONS		LBLIDBASE + 0x02E0
#define IDC_LBLLALLBLRSOFFTHRSHLD	LBLIDBASE + 0x02E1

#define IDC_TXTLLFROSTPROTENABLE	TXTIDBASE + 0x0214
#define IDC_TXTLLFROSTPROTRATE		TXTIDBASE + 0x0215
#define IDC_TXTLLSLAVEENABLE		TXTIDBASE + 0x0220
#define IDC_TXTLLMASTERENABLE		TXTIDBASE + 0x0221
#define IDC_TXTLLSETPOINT			TXTIDBASE + 0x0222
#define IDC_TXTLLTODSETPOINT		TXTIDBASE + 0x0223
#define IDC_TXTLLODRESETNABLE		TXTIDBASE + 0x0224
#define IDC_TXTLLONHYSTERESIS		TXTIDBASE + 0x0225
#define IDC_TXTLLOFFHYSTERESIS		TXTIDBASE + 0x0226
#define IDC_TXTLLHYSTSTEPTIME		TXTIDBASE + 0x0227
#define IDC_TXTLLPGAIN				TXTIDBASE + 0x0228
#define IDC_TXTLLIGAIN				TXTIDBASE + 0x0229
#define IDC_TXTLLDGAIN				TXTIDBASE + 0x022A
#define IDC_TXTLLOPERATIONSWITCH	TXTIDBASE + 0x022B
#define IDC_TXTLLCHDEMANDSWITCH		TXTIDBASE + 0x022C
#define IDC_TXTLLCHSETPOINTSRC		TXTIDBASE + 0x022D
#define IDC_TXTLLMODULATIONSENSOR	TXTIDBASE + 0x022E
#define IDC_TXTLLBACKUPMODSENSOR	TXTIDBASE + 0x022F
#define IDC_TXTLLCH4MATEMP			TXTIDBASE + 0x0230
#define IDC_TXTLLCH20MATEMP			TXTIDBASE + 0x0231
#define IDC_TXTLLCHMODBUSSETPOINT	TXTIDBASE + 0x0232
#define IDC_TXTLLCHMODBUSSTAT		TXTIDBASE + 0x0233
#define IDC_TXTLLSLAVEMODE			TXTIDBASE + 0x0234
#define IDC_TXTLLSLAVECOMMAND		TXTIDBASE + 0x0235
#define IDC_TXTLLBASELOADRATE		TXTIDBASE + 0x0236
#define IDC_TXTLLFANDOCRATE			TXTIDBASE + 0x0237
#define IDC_TXTLLSLAVESEQORDER		TXTIDBASE + 0x0238
#define IDC_TXTLLMODBUSPORT			TXTIDBASE + 0x0239
#define IDC_TXTLLSLAVEDTFDELAY		TXTIDBASE + 0x023A
#define IDC_TXTLLSLAVECAPACITY		TXTIDBASE + 0x023B
#define IDC_TXTLLBASELDCOMMRATE		TXTIDBASE + 0x023C
#define IDC_TXTLLRATEALLOCMETHOD	TXTIDBASE + 0x023D
#define IDC_TXTLLLEADALLOCMETHOD	TXTIDBASE + 0x023E
#define IDC_TXTLLLAGALLOCMETHOD		TXTIDBASE + 0x023F
#define IDC_TXTLLDHWDEMANDSW		TXTIDBASE + 0x02C0
#define IDC_TXTLLDHWSETPOINT		TXTIDBASE + 0x02C1
#define IDC_TXTLLDHWPRIORITYVSCH	TXTIDBASE + 0x02C2
#define IDC_TXTLLRESERVED01			TXTIDBASE + 0x02C3
#define IDC_TXTLLRESERVED02			TXTIDBASE + 0x02C4
#define IDC_TXTLLRESERVED03			TXTIDBASE + 0x02C5
#define IDC_TXTLLRESERVED04			TXTIDBASE + 0x02C6
#define IDC_TXTLLRESERVED05			TXTIDBASE + 0x02C7
#define IDC_TXTLLRESERVED06			TXTIDBASE + 0x02C8
#define IDC_TXTLLSLVDROPOUTRTNCOMP	TXTIDBASE + 0x02C9
#define IDC_TXTLLADDSTGMTHD			TXTIDBASE + 0x02CA
#define IDC_TXTLLRESERVED07			TXTIDBASE + 0x02CB
#define IDC_TXTLLADDSTGDTCTTIME		TXTIDBASE + 0x02CC
#define IDC_TXTLLRESERVED08			TXTIDBASE + 0x02CD
#define IDC_TXTLLADDSTGERRTHRSHLD	TXTIDBASE + 0x02CE
#define IDC_TXTLLADDSTGRATEOFFSET	TXTIDBASE + 0x02CF
#define IDC_TXTLLADDSTGERRGAIN		TXTIDBASE + 0x02D0
#define IDC_TXTLLADDSTGRATEGAIN		TXTIDBASE + 0x02D1
#define IDC_TXTLLADDSTGINTRSTGDLY	TXTIDBASE + 0x02D2
#define IDC_TXTLLDROPSTGMTHD		TXTIDBASE + 0x02D3
#define IDC_TXTLLRESERVED09			TXTIDBASE + 0x02D4
#define IDC_TXTLLDROPSTGDTCTTIME	TXTIDBASE + 0x02D5
#define IDC_TXTLLRESERVED10			TXTIDBASE + 0x02D6
#define IDC_TXTLLDROPSTGERRTHRSHLD	TXTIDBASE + 0x02D7
#define IDC_TXTLLDROPSTGRATEOFFSET	TXTIDBASE + 0x02D8
#define IDC_TXTLLDROPSTGERRGAIN		TXTIDBASE + 0x02D9
#define IDC_TXTLLDROPSTGRATEGAIN	TXTIDBASE + 0x02DA
#define IDC_TXTLLDROPSTGINTRSTGDLY	TXTIDBASE + 0x02DB
#define IDC_TXTLLRESERVED11			TXTIDBASE + 0x02DC
#define IDC_TXTLLEADROTNTIME		TXTIDBASE + 0x02DD
#define IDC_TXTLFRCLEADROTNTIME		TXTIDBASE + 0x02DE
#define IDC_TXTLDHWTODSETPOINT		TXTIDBASE + 0x02DF
#define IDC_TXTLBLROFFOPTIONS		TXTIDBASE + 0x02E0
#define IDC_TXTLALLBLRSOFFTHRSHLD	TXTIDBASE + 0x02E1

#define IDC_LLHYSTSTHOURSPIN		HHSPINIDBASE + 0x0227
#define IDC_LLHYSTSTMINSPIN			MMSPINIDBASE + 0x0227
#define IDC_LLHYSTSTSECSPIN			SSSPINIDBASE + 0x0227
#define IDC_LLHYSTSTHOUREDIT		HHEDITIDBASE + 0x0227
#define IDC_LLHYSTSTMINEDIT			MMEDITIDBASE + 0x0227
#define IDC_LLHYSTSTSECEDIT			SSEDITIDBASE + 0x0227

#define IDC_LBLBIT00				LBLIDBASE + 0x0001
#define IDC_LBLBIT01				LBLIDBASE + 0x0002
#define IDC_LBLBIT02				LBLIDBASE + 0x0004
#define IDC_LBLBIT03				LBLIDBASE + 0x0008
#define IDC_LBLBIT04				LBLIDBASE + 0x0010
#define IDC_LBLBIT05				LBLIDBASE + 0x0020
#define IDC_LBLBIT06				LBLIDBASE + 0x0040
#define IDC_LBLBIT07				LBLIDBASE + 0x0080
#define IDC_LBLBIT08				LBLIDBASE + 0x0100
#define IDC_LBLBIT09				LBLIDBASE + 0x0200
#define IDC_LBLBIT0A				LBLIDBASE + 0x0400
#define IDC_LBLBIT0B				LBLIDBASE + 0x0800
#define IDC_LBLBIT0C				LBLIDBASE + 0x1000
#define IDC_LBLBIT0D				LBLIDBASE + 0x2000
#define IDC_LBLBIT0E				LBLIDBASE + 0x4000
#define IDC_LBLBIT0F				LBLIDBASE + 0x8000
#define IDD_INDICATOR00				1
#define IDD_INDICATOR01				2
#define IDD_INDICATOR02				3
#define IDD_INDICATOR03				4
#define IDD_INDICATOR04				5
#define IDD_INDICATOR05				6
#define IDD_INDICATOR06				7
#define IDD_INDICATOR07				8
#define IDD_INDICATOR08				9
#define IDD_INDICATOR09				0x0a
#define IDD_INDICATOR0A				0x0b
#define IDD_INDICATOR0B				0x0c
#define IDD_INDICATOR0C				0x0d
#define IDD_INDICATOR0D				0x0e
#define IDD_INDICATOR0E				0x0f
#define IDD_INDICATOR0F				0x10

#define IDC_LBLBIT4001				LBLIDBASE + 0x4001
#define IDC_LBLBIT4002				LBLIDBASE + 0x4002
#define IDC_LBLBIT4004				LBLIDBASE + 0x4004
#define IDC_LBLBIT4008				LBLIDBASE + 0x4008
#define IDC_LBLBIT4010				LBLIDBASE + 0x4010
#define IDC_LBLBIT4020				LBLIDBASE + 0x4020
#define IDC_LBLBIT4040				LBLIDBASE + 0x4040
#define IDC_LBLBIT4080				LBLIDBASE + 0x4080
#define IDC_LBLBIT4100				LBLIDBASE + 0x4100
#define IDC_LBLBIT4200				LBLIDBASE + 0x4200
#define IDC_LBLBIT4400				LBLIDBASE + 0x4400
#define IDD_INDICATOR4101			0x4101
#define IDD_INDICATOR4102			0x4102
#define IDD_INDICATOR4103			0x4103
#define IDD_INDICATOR4104			0x4104
#define IDD_INDICATOR4105			0x4105
#define IDD_INDICATOR4106			0x4106
#define IDD_INDICATOR4107			0x4107
#define IDD_INDICATOR4108			0x4108
#define IDD_INDICATOR4109			0x4109
#define IDD_INDICATOR410a			0x410a
#define IDD_INDICATOR410b			0x410b


#define IDC_LBLPRODUCTTYPE			LBLIDBASE + 0x00B0
#define IDC_LBLTEMPUNITS			LBLIDBASE + 0x00B2
#define IDC_LBLASCTIME				LBLIDBASE + 0x00B3
#define IDC_LBLALARMSILENCETIME		LBLIDBASE + 0x00B4
#define IDC_LBLBURNERNAME			LBLIDBASE + 0x00B7
#define IDC_LBLINSTALLATIONDATA		LBLIDBASE + 0x00B8
#define IDC_LBLOSNUMBER				LBLIDBASE + 0x00BA
#define IDC_LBLDATECODE				LBLIDBASE + 0x00BB
#define IDC_LBLSAFETYBUILD			LBLIDBASE + 0x00BC
#define IDC_LBLAPPBUILD				LBLIDBASE + 0x00BD
#define IDC_LBLBURNERCYCLES			LBLIDBASE + 0x0080
#define IDC_LBLBURNERHOURS			LBLIDBASE + 0x0082
#define IDC_LBLCHPUMPCYCLES			LBLIDBASE + 0x0084
#define IDC_LBLDHWPUMPCYCLES		LBLIDBASE + 0x0086
#define IDC_LBLSYSPUMPCYCLES		LBLIDBASE + 0x0088
#define IDC_LBLBLRPUMPCYCLES		LBLIDBASE + 0x008A
#define IDC_LBLAUXPUMPCYCLES		LBLIDBASE + 0x008C
#define IDC_LBLCTRLRCYCLES			LBLIDBASE + 0x008E
#define IDC_LBLCTRLRRUNTIME			LBLIDBASE + 0x0090
#define IDC_LBLAUX2PUMPCYCLES		LBLIDBASE + 0x0092
#define IDC_LBLSYSTEMRESETRESTART	LBLIDBASE + 0x00B6
#define IDC_LBLPOWERLINEFREQ		LBLIDBASE + 0x0276
#define IDC_LBLSOFTLOCKOUTENABLE	LBLIDBASE + 0x027E
#define IDC_LBLBURNEROFFINHIBITTIME	LBLIDBASE + 0x027F
#define IDC_LBLSTPDMODSTRTOFFSET	LBLIDBASE + 0x0298
#define IDC_LBLSTPDMODRCYCLOFFSET	LBLIDBASE + 0x0299
#define IDC_LBLPRFRDLIGHTOFFRATE	LBLIDBASE + 0x029A
#define IDC_LBLANALOGRATETRACKING	LBLIDBASE + 0x029B
#define IDC_LBLMODBUSANALOGOUTPUT	LBLIDBASE + 0x029C
#define IDC_LBLMODBUSANALOGOUTPUTCONTROL	LBLIDBASE + 0x029D
#define IDC_LBLIASOPENMODULATIONSTEPDOWNRATE	LBLIDBASE + 0x029E
#define IDC_LBLIASOPENMODULATIONSTEPDOWNTIME	LBLIDBASE + 0x029F

#define IDC_TXTPRODUCTTYPE			TXTIDBASE + 0x00B0
#define IDC_TXTTEMPUNITS			TXTIDBASE + 0x00B2
#define IDC_TXTASCTIME				TXTIDBASE + 0x00B3
#define IDC_TXTALARMSILENCETIME		TXTIDBASE + 0x00B4
#define IDC_TXTBURNERNAME			TXTIDBASE + 0x00B7
#define IDC_TXTINSTALLATIONDATA		TXTIDBASE + 0x00B8
#define IDC_TXTOEMID				TXTIDBASE + 0x00B9
#define IDC_TXTOSNUMBER				TXTIDBASE + 0x00BA
#define IDC_TXTDATECODE				TXTIDBASE + 0x00BB
#define IDC_TXTSAFETYBUILD			TXTIDBASE + 0x00BC
#define IDC_TXTAPPBUILD				TXTIDBASE + 0x00BD
#define IDC_TXTBURNERCYCLES			TXTIDBASE + 0x0080
#define IDC_TXTBURNERHOURS			TXTIDBASE + 0x0082
#define IDC_TXTCHPUMPCYCLES			TXTIDBASE + 0x0084
#define IDC_TXTDHWPUMPCYCLES		TXTIDBASE + 0x0086
#define IDC_TXTSYSPUMPCYCLES		TXTIDBASE + 0x0088
#define IDC_TXTBLRPUMPCYCLES		TXTIDBASE + 0x008A
#define IDC_TXTAUXPUMPCYCLES		TXTIDBASE + 0x008C
#define IDC_TXTCTRLRCYCLES			TXTIDBASE + 0x008E
#define IDC_TXTCTRLRRUNTIME			TXTIDBASE + 0x0090
#define IDC_TXTAUX2PUMPCYCLES		TXTIDBASE + 0x0092
#define IDC_TXTSYSTEMRESETRESTART	TXTIDBASE + 0x00B6
#define IDC_TXTPOWERLINEFREQ		TXTIDBASE + 0x0276
#define IDC_TXTSOFTLOCKOUTENABLE	TXTIDBASE + 0x027E
#define IDC_TXTBURNEROFFINHIBITTIME	TXTIDBASE + 0x027F
#define IDC_TXTSTPDMODSTRTOFFSET	TXTIDBASE + 0x0298
#define IDC_TXTSTPDMODRCYCLOFFSET	TXTIDBASE + 0x0299
#define IDC_TXTPRFRDLIGHTOFFRATE	TXTIDBASE + 0x029A
#define IDC_TXTANALOGRATETRACKING	TXTIDBASE + 0x029B
#define IDC_TXTMODBUSANALOGOUTPUT	TXTIDBASE + 0x029C
#define IDC_TXTMODBUSANALOGOUTPUTCONTROL	TXTIDBASE + 0x029D
#define IDC_TXTIASOPENMODULATIONSTEPDOWNRATE	TXTIDBASE + 0x029E
#define IDC_TXTIASOPENMODULATIONSTEPDOWNTIME	TXTIDBASE + 0x029F

#define IDC_ASCTIMEHOURSPIN			HHSPINIDBASE + 0x00B3
#define IDC_ASCTIMEMINSPIN			MMSPINIDBASE + 0x00B3
#define IDC_ASCTIMESECSPIN			SSSPINIDBASE + 0x00B3
#define IDC_ASCTIMEHOUREDIT			HHEDITIDBASE + 0x00B3
#define IDC_ASCTIMEMINEDIT			MMEDITIDBASE + 0x00B3
#define IDC_ASCTIMESECEDIT			SSEDITIDBASE + 0x00B3

#define IDC_LBLODRMAXODTEMP			LBLIDBASE + 0x0200
#define IDC_LBLODRMINODTEMP			LBLIDBASE + 0x0201
#define IDC_LBLODRCHLWTEMP			LBLIDBASE + 0x0202
#define IDC_LBLODRCHBOOSTTIME		LBLIDBASE + 0x0203
#define IDC_LBLODRCHMAXOFFPT		LBLIDBASE + 0x0204
#define IDC_LBLODRLLMAXODTEMP		LBLIDBASE + 0x0205
#define IDC_LBLODRLLMINODTEMP		LBLIDBASE + 0x0206
#define IDC_LBLODRLLLWTEMP			LBLIDBASE + 0x0207
#define IDC_LBLODRLLBOOSTTIME		LBLIDBASE + 0x0208
#define IDC_LBLODRLLMAXOFFPT		LBLIDBASE + 0x0209
#define IDC_LBLODRCHBOOSTSTEP		LBLIDBASE + 0x020A
#define IDC_LBLODRCHBOOSTRCVRYSTEPTIME		LBLIDBASE + 0x020B
#define IDC_LBLODRLLBOOSTSTEP		LBLIDBASE + 0x020C
#define IDC_LBLODRLLBOOSTRCVRYSTEPTIME		LBLIDBASE + 0x020D
#define IDC_LBLODRMINBOILERWATERTEMP		LBLIDBASE + 0x020E
#define IDC_LBLODRLLMINWATERTEMP	LBLIDBASE + 0x020F

#define IDC_TXTODRMAXODTEMP			TXTIDBASE + 0x0200
#define IDC_TXTODRMINODTEMP			TXTIDBASE + 0x0201
#define IDC_TXTODRCHLWTEMP			TXTIDBASE + 0x0202
#define IDC_TXTODRCHBOOSTTIME		TXTIDBASE + 0x0203
#define IDC_TXTODRCHMAXOFFPT		TXTIDBASE + 0x0204
#define IDC_TXTODRLLMAXODTEMP		TXTIDBASE + 0x0205
#define IDC_TXTODRLLMINODTEMP		TXTIDBASE + 0x0206
#define IDC_TXTODRLLLWTEMP			TXTIDBASE + 0x0207
#define IDC_TXTODRLLBOOSTTIME		TXTIDBASE + 0x0208
#define IDC_TXTODRLLMAXOFFPT		TXTIDBASE + 0x0209
#define IDC_TXTODRCHBOOSTSTEP		TXTIDBASE + 0x020A
#define IDC_TXTODRCHBOOSTRCVRYSTEPTIME		TXTIDBASE + 0x020B
#define IDC_TXTODRLLBOOSTSTEP		TXTIDBASE + 0x020C
#define IDC_TXTODRLLBOOSTRCVRYSTEPTIME		TXTIDBASE + 0x020D
#define IDC_TXTODRMINBOILERWATERTEMP		TXTIDBASE + 0x020E
#define IDC_TXTODRLLMINWATERTEMP	TXTIDBASE + 0x020F
#define IDC_ODRESETHOUREDIT			HHEDITIDBASE + 0x0200
#define IDC_ODRESETMINEDIT			MMEDITIDBASE + 0x0200
#define IDC_ODRESETSECEDIT			SSEDITIDBASE + 0x0200

#define IDC_LBLLLMASTERSTATUS		LBLIDBASE + 0x00A0
#define IDC_LBLLLSLAVESTATUS		LBLIDBASE + 0x00A1
#define IDC_LBLLLMASTERSPSRC		LBLIDBASE + 0x00A2
#define IDC_LBLLLMASTERHEATDMND		LBLIDBASE + 0x00A3
#define IDC_LBLLLSLAVEBURNERDMND	LBLIDBASE + 0x00A4
#define IDC_LBLLLSLAVEREQRATE		LBLIDBASE + 0x00A5

#define IDC_TXTLLMASTERSTATUS		TXTIDBASE + 0x00A0
#define IDC_TXTLLSLAVESTATUS		TXTIDBASE + 0x00A1
#define IDC_TXTLLMASTERSPSRC		TXTIDBASE + 0x00A2
#define IDC_TXTLLMASTERHEATDMND		TXTIDBASE + 0x00A3
#define IDC_TXTLLSLAVEBURNERDMND	TXTIDBASE + 0x00A4
#define IDC_TXTLLSLAVEREQRATE		TXTIDBASE + 0x00A5

#define IDC_LBLXLLACTIVESERVICE		LBLIDBASE + 0x0300
#define IDC_TXTXLLACTIVESERVICE		TXTIDBASE + 0x0300

#define IDC_LBLXLLSLAVE1ADDR			LBLIDBASE + 0x0301
#define IDC_LBLXLLSLAVE1STATE		LBLIDBASE + 0x0302
#define IDC_LBLXLLSLAVE1STGORDER		LBLIDBASE + 0x0303
#define IDC_LBLXLLSLAVE1FIRINGRATE	LBLIDBASE + 0x0304

#define IDC_LBLXLLSLAVE2ADDR			LBLIDBASE + 0x0305
#define IDC_LBLXLLSLAVE2STATE		LBLIDBASE + 0x0306
#define IDC_LBLXLLSLAVE2STGORDER		LBLIDBASE + 0x0307
#define IDC_LBLXLLSLAVE2FIRINGRATE	LBLIDBASE + 0x0308

#define IDC_LBLXLLSLAVE3ADDR			LBLIDBASE + 0x0309
#define IDC_LBLXLLSLAVE3STATE		LBLIDBASE + 0x030A
#define IDC_LBLXLLSLAVE3STGORDER		LBLIDBASE + 0x030B
#define IDC_LBLXLLSLAVE3FIRINGRATE	LBLIDBASE + 0x030C

#define IDC_LBLXLLSLAVE4ADDR			LBLIDBASE + 0x030D
#define IDC_LBLXLLSLAVE4STATE		LBLIDBASE + 0x030E
#define IDC_LBLXLLSLAVE4STGORDER		LBLIDBASE + 0x030F
#define IDC_LBLXLLSLAVE4FIRINGRATE	LBLIDBASE + 0x0310

#define IDC_LBLXLLSLAVE5ADDR			LBLIDBASE + 0x0311
#define IDC_LBLXLLSLAVE5STATE		LBLIDBASE + 0x0312
#define IDC_LBLXLLSLAVE5STGORDER		LBLIDBASE + 0x0313
#define IDC_LBLXLLSLAVE5FIRINGRATE	LBLIDBASE + 0x0314

#define IDC_LBLXLLSLAVE6ADDR			LBLIDBASE + 0x0315
#define IDC_LBLXLLSLAVE6STATE		LBLIDBASE + 0x0316
#define IDC_LBLXLLSLAVE6STGORDER		LBLIDBASE + 0x0317
#define IDC_LBLXLLSLAVE6FIRINGRATE	LBLIDBASE + 0x0318

#define IDC_LBLXLLSLAVE7ADDR			LBLIDBASE + 0x0319
#define IDC_LBLXLLSLAVE7STATE		LBLIDBASE + 0x031A
#define IDC_LBLXLLSLAVE7STGORDER		LBLIDBASE + 0x031B
#define IDC_LBLXLLSLAVE7FIRINGRATE	LBLIDBASE + 0x031C

#define IDC_LBLXLLSLAVE8ADDR			LBLIDBASE + 0x031D
#define IDC_LBLXLLSLAVE8STATE		LBLIDBASE + 0x031E
#define IDC_LBLXLLSLAVE8STGORDER		LBLIDBASE + 0x031F
#define IDC_LBLXLLSLAVE8FIRINGRATE	LBLIDBASE + 0x0320

#define IDC_TXTXLLSLAVE1ADDR			TXTIDBASE + 0x0301
#define IDC_TXTXLLSLAVE1STATE		TXTIDBASE + 0x0302
#define IDC_TXTXLLSLAVE1STGORDER		TXTIDBASE + 0x0303
#define IDC_TXTXLLSLAVE1FIRINGRATE	TXTIDBASE + 0x0304

#define IDC_TXTXLLSLAVE2ADDR			TXTIDBASE + 0x0305
#define IDC_TXTXLLSLAVE2STATE		TXTIDBASE + 0x0306
#define IDC_TXTXLLSLAVE2STGORDER		TXTIDBASE + 0x0307
#define IDC_TXTXLLSLAVE2FIRINGRATE	TXTIDBASE + 0x0308

#define IDC_TXTXLLSLAVE3ADDR			TXTIDBASE + 0x0309
#define IDC_TXTXLLSLAVE3STATE		TXTIDBASE + 0x030A
#define IDC_TXTXLLSLAVE3STGORDER		TXTIDBASE + 0x030B
#define IDC_TXTXLLSLAVE3FIRINGRATE	TXTIDBASE + 0x030C

#define IDC_TXTXLLSLAVE4ADDR			TXTIDBASE + 0x030D
#define IDC_TXTXLLSLAVE4STATE		TXTIDBASE + 0x030E
#define IDC_TXTXLLSLAVE4STGORDER		TXTIDBASE + 0x030F
#define IDC_TXTXLLSLAVE4FIRINGRATE	TXTIDBASE + 0x0310

#define IDC_TXTXLLSLAVE5ADDR			TXTIDBASE + 0x0311
#define IDC_TXTXLLSLAVE5STATE		TXTIDBASE + 0x0312
#define IDC_TXTXLLSLAVE5STGORDER		TXTIDBASE + 0x0313
#define IDC_TXTXLLSLAVE5FIRINGRATE	TXTIDBASE + 0x0314

#define IDC_TXTXLLSLAVE6ADDR			TXTIDBASE + 0x0315
#define IDC_TXTXLLSLAVE6STATE		TXTIDBASE + 0x0316
#define IDC_TXTXLLSLAVE6STGORDER		TXTIDBASE + 0x0317
#define IDC_TXTXLLSLAVE6FIRINGRATE	TXTIDBASE + 0x0318

#define IDC_TXTXLLSLAVE7ADDR			TXTIDBASE + 0x0319
#define IDC_TXTXLLSLAVE7STATE		TXTIDBASE + 0x031A
#define IDC_TXTXLLSLAVE7STGORDER		TXTIDBASE + 0x031B
#define IDC_TXTXLLSLAVE7FIRINGRATE	TXTIDBASE + 0x031C

#define IDC_TXTXLLSLAVE8ADDR			TXTIDBASE + 0x031D
#define IDC_TXTXLLSLAVE8STATE		TXTIDBASE + 0x031E
#define IDC_TXTXLLSLAVE8STGORDER		TXTIDBASE + 0x031F
#define IDC_TXTXLLSLAVE8FIRINGRATE	TXTIDBASE + 0x0320

#define IDC_LBLXLLLEADBOILERADDR	LBLIDBASE + 0x0321
#define IDC_LBLXLLMASTERFIRINGRATE	LBLIDBASE + 0x0322

#define IDC_TXTXLLLEADBOILERADDR	TXTIDBASE + 0x0321
#define IDC_TXTXLLMASTERFIRINGRATE	TXTIDBASE + 0x0322

#define IDC_TXTLOCKOUTCODE			TXTIDBASE + 0x0360
#define IDC_TXTLOCKOUTCYCLE			TXTIDBASE + 0x0368
#define IDC_TXTLOCKOUTHOURS			TXTIDBASE + 0x036C
#define IDC_TXTLOCKOUTSTATE			TXTIDBASE + 0x0364
#define IDC_TXTLOCKOUTSEQTIME		TXTIDBASE + 0x0366
#define IDC_TXTLOCKOUT1STOUT		TXTIDBASE + 0x0362

#define TXTLRDIDBASE				16000
#define IDC_TXTLRDPUMPA				TXTLRDIDBASE
#define IDC_TXTLRDPUMPB				TXTLRDIDBASE + 1
#define IDC_TXTLRDPUMPC				TXTLRDIDBASE + 2
#define IDC_TXTLRDBLOWERHSI			TXTLRDIDBASE + 3
#define IDC_TXTLRDEXTIGN			TXTLRDIDBASE + 4
#define IDC_TXTLRDPILOTVALVE		TXTLRDIDBASE + 5
#define IDC_TXTLRDMAINVALVE			TXTLRDIDBASE + 6
#define IDC_TXTLRDALARM				TXTLRDIDBASE + 7
#define IDC_TXTLRDSTAT				TXTLRDIDBASE + 13
#define IDC_TXTLRDTOD				TXTLRDIDBASE + 14
#define IDC_TXTSAFETYRELAY			TXTLRDIDBASE + 15
#define IDC_TXTLRDINLET				TXTLRDIDBASE + 16
#define IDC_TXTLRDOUTLET			TXTLRDIDBASE + 17
#define IDC_TXTLRDDHW				TXTLRDIDBASE + 18
#define IDC_TXTLRDOUTDOOR			TXTLRDIDBASE + 19
#define IDC_TXTLRDSTACK				TXTLRDIDBASE + 20
#define IDC_TXTLRD420MA				TXTLRDIDBASE + 21
#define IDC_TXTLRDDATA				TXTLRDIDBASE + 22

#define IDC_TXTXLLSTATUSARRAYSIZE	15000

#define IDC_BTNRTUSD			500
#define IDC_BTNTCP				501
#define IDC_COMPORTCOMBO		502
#define MAXCOMPORTS				20
#if 0
#define IDC_BTNCOM1				500
#define IDC_BTNCOM2				501
#define IDC_BTNCOM3				502
#define IDC_BTNCOM4				503
#define IDC_BTNCOM5				504
#define IDC_BTNCOM6				505
#endif
#define IDC_STATUSCONNECTING	506
#define IDC_STATUSUPDATING		507
/*#define IDC_MBADDREDIT			508*/
#define IDC_CBMBADDR			508
#define IDC_UPDCOUNT			509
#define IDC_BTNCLRLOCKOUT		510
#define IDC_BTNRTUSG			511
#define IDC_TCPGWCOMBO			512

#define IDS_NAMEFILTER			4000
#define IDS_DEFAULTNAME			4001
#define IDS_DEFAULTEXT			4002

#define IDC_BTNCONNECT			5000
#define IDC_CHKSAVEDATA			5001
#define IDC_ALERTLIST			5002
#define IDC_BTNLOGIN			5003
#define IDC_EDITLOGIN			5004
#define IDC_TXTREGISTERACCESS	5005
#define IDC_LOCKOUTLIST			5006
#define IDC_LOCKOUTRCRDLIST		5007
#define IDC_EDITPORT			5008
#define DEFAULTMBPORT			_T("502")
#define	IDC_SAVEDATASECSEDIT	5009
#define IDC_SAVEDATASECINTER	5010
#define IDC_BTNIPADDRESS		5011
#define IDC_TXTTXHB				5012
#define IDC_TXTRXHB				5013
#define IDC_BTNPOLLDLG			5014
#define IDC_POLLTOTALSENT		5015
#define IDC_POLLTOTALRCVD		5016
#define IDC_POLLTOTALERRORS		5017
#define IDC_POLLINTERVALCOMBO	5018
#define IDC_BTNPOLLINTERVALAPPLY	5019
#define IDC_BTNSAVECONFIG		5020
#define IDC_BTNLOADCONFIG		5021
#define IDC_POLLCONNECTTIME		5022
#define IDC_POLLERRORRATE		5023
#define IDC_BTNPOLLRESYNC		5024
#define IDC_BTNAUTOID			5025
#define IDC_BTNTESTING			5026
#define IDC_LBLALARMALERT		5027
#define IDC_TXTALARMALERT		5028
#define IDS_SUMMARYPAGE			6000
#define IDS_CHCONFIGPAGE		6001
#define IDS_ENABLE				6002
#define IDS_DISABLE				6003
#define IDS_SENSORONLY			6004
#define IDS_SENSORANDSTAT		6005
#define IDS_SENSORANDREMOTE		6006
#define IDS_LCIANDSENSOR		6007
#define IDS_UNCONFIGURED		6008
#define IDS_CONNECTING			6009
#define IDS_DIGITALIOPAGE		6010
#define IDS_ALERTLOGPAGE		6011
#define IDS_SYSTEMIDPAGE		6012
#define IDS_ODRESETCFGPAGE		6013
#define IDS_ODRESETLINEWND		6014
#define IDS_DHWCONFIGPAGE		6015
#define IDS_LLSTATUSPAGE		6016
#define IDS_LLCONFIGPAGE		6017
#define IDS_LOCKOUTLOGPAGE		6018
#define IDS_MODCONFIGPAGE		6019
#define IDS_BCCONFIGPAGE		6020
#define IDS_LIMCONFIGPAGE		6021
#define IDS_PUMPCONFIGPAGE		6022
#define IDS_SAVERESTOREPAGE		6023
#define IDS_SENSORSTATUSNONE	6024
#define IDS_SENSORSTATUSNORMAL	6025
#define IDS_SENSORSTATUSOPEN	6026
#define IDS_SENSORSTATUSSHORTED	6027
#define IDS_SENSORSTATUSOUTSIDEHIGHRANGE 6028
#define IDS_SENSORSTATUSOUTSIDELOWRANGE	6029
#define IDS_SENSORSTATUSNOTRELIABLE	6030


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
